### ISSUE TITLE
Response Generation Quantity Issue

### ISSUE THREAD

**Issue by MatthewBoeding** [Mazurel/Modbus#3]
When parsing a request to generate a read coils response, the number of inputs is not parsed correctly. The bytes value should be a uint16_t instead of uint8_t. The standard requires 0x0000-0xFFFF. Currently, if you're value is 0x0000-0x00FF, you won't generate any value bytes. 

https://github.com/Mazurel/Modbus/blob/9bd2ad492df05f9817bce2437d6195d875231c83/src/modbusResponse.cpp#L46-L51

You'll also need to change the value to be read:

```
uint16_t bytes; 
  
switch (_functionCode) { 
    case utils::ReadDiscreteOutputCoils: 
    case utils::ReadDiscreteInputContacts: 
    bytes = inputData[2] << 8 + inputData[3]; 
```

**Comment by Mazurel** [comment]
Interesting, I don't have access to the Modbus standard right now, but I will look for it. I was basing this on descriptions from simply modbus: https://www.simplymodbus.ca/FC02.htm

There you can see, that in response, there is only one byte to describe the amount of bytes:
![image](https://github.com/user-attachments/assets/277eb1a8-8494-46b2-ae7d-bcd784e44263)

**Comment by MatthewBoeding** [comment]
First, thank you for your response and all the work on this library!

You are correct, the response packet is correctly generated for the size of each field. I should clarify the issue is solely with parsing a request in the response constructor. I'm using this as a reference for packet testing: https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf
![image](https://github.com/user-attachments/assets/1df13a85-a399-4024-9b8e-fe7c07aeca93)

In testing with a packet similar to this. If the request packet is generated with anything more than 255 in the third argument, it gets casted to 0.  

```
MB::ModbusRequest request(1, MB::utils::ReadDiscreteOutputCoils, 100, 10);  
std::vector<uint8_t> pack = request.toRaw();
 
MB::ModbusResponse response(pack, bool(false)); 
```

Actually, looking at the Modbus Request Constructor, the address may be being interpreted as the quantity:
https://github.com/Mazurel/Modbus/blob/7d5352a684a197d47df49e3581e64f6e58808557/src/modbusRequest.cpp#L13-L17

So the read packets are interpreting the address as the quantity:
https://github.com/Mazurel/Modbus/blob/9bd2ad492df05f9817bce2437d6195d875231c83/src/modbusResponse.cpp#L48-L51

https://github.com/Mazurel/Modbus/blob/9bd2ad492df05f9817bce2437d6195d875231c83/src/modbusResponse.cpp#L59-L61

I may look at tinkering with this and put in a pull request if you are interested.

**Comment by Mazurel** [comment]
I will quickly look at it and try to prepare some test case for it. It seems not that complicated.

I will try to make a PR (and mention you there), if I will have any problems with that, I will ask you for some help

**Comment by Mazurel** [comment]
@MatthewBoeding please take a look at PR #12 - it should resolve this issue, I have also added some more tests around that area.

**Comment by Mazurel** [comment]
Ok, I am closing this issue, fix is on the `master` branch.

Feel free to reopen or open new one if needed, thanks for cooperation !
